In [3]:
import time

# 获取当前的本地时间 (struct_time 对象)
current_local_time = time.localtime()
print(current_local_time)
# 将时间格式化为 "年-月-日 时:分:秒" 的字符串
beijing_time_str = time.strftime("%H:%M:%S", current_local_time)

print(f"当前系统时间: {beijing_time_str}")

time.struct_time(tm_year=2025, tm_mon=5, tm_mday=20, tm_hour=11, tm_min=39, tm_sec=31, tm_wday=1, tm_yday=140, tm_isdst=0)
当前系统时间: 11:39:31


In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import RFE
from sklearn.decomposition import PCA



X_train = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
y_train = [0, 1, 0, 1]

clf = RandomForestClassifier()
clf.fit(X_train, y_train)

# 获取特征重要性
importances = clf.feature_importances_
print(importances)

# 使用线性模型进行递归特征消除
rfe = RFE(clf, n_features_to_select=1)  
X_rfe = rfe.fit_transform(X_train, y_train)
print(X_rfe)

# 假设 X 是特征矩阵
pca = PCA(n_components=2)  # 降维到 2 个主成分
X_pca = pca.fit_transform(X_train)
print(X_pca)

[0.34469697 0.39015152 0.26515152]
[[ 3]
 [ 6]
 [ 9]
 [12]]
[[-7.79422863  0.        ]
 [-2.59807621  0.        ]
 [ 2.59807621  0.        ]
 [ 7.79422863 -0.        ]]


In [24]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

# 假设 X 是特征矩阵，y 是目标变量
lda = LinearDiscriminantAnalysis(n_components=1)  # 降维到 2 个线性判别组件
X_lda = lda.fit_transform(X_train, y_train)
print(X_lda)

[[-1.06066017]
 [-0.35355339]
 [ 0.35355339]
 [ 1.06066017]]


In [33]:
import json

with open(r'D:\code\curie\inference\multi_runs\current\dft\extract_dft_metadata_1_shot\doubao-1.5-thinking-pro\run_1\success\2023_09_22_7c5bbe7e076779b790ccg.json', 'r') as f:
    data = json.load(f)
print(data)
response = data['response_text']
# print(response)
response=json.loads(response)
print(response)
response[0]['basis_set']

{'record_id': '2023_09_22_7c5bbe7e076779b790ccg', 'model_id': 'doubao-1.5-thinking-pro', 'prompt_path': '../prompts/extract_dft_metadata_1_shot.txt', 'reasoning_content': 'Okay, let\'s start by carefully reading the paper to find all the DFT calculations mentioned. The user wants a JSON list of distinct DFT parameters with specific fields. \n\nFirst, the paper mentions in the "DFT calculations" section: "a density functional geometry optimization (fixed experimental unit cell) was carried out using CRYSTAL14 (Dovesi et al., 2014)". So the software is CRYSTAL14.\n\nNext, the functional: "the B3LYP functional" is explicitly stated. So functional is B3LYP.\n\nK-points: "used 8 k points". But the format requires k-point grid as [x,y,z]. The paper says "8 k points", but it\'s not clear if that\'s a grid. Maybe it\'s a Monkhorst-Pack grid, but the exact grid isn\'t specified. So k-points might be "8" but the example uses [x,y,z]. Since the paper doesn\'t specify the grid dimensions, maybe we

'Basis sets for C, H, O: Peintinger et al. (2012); basis set for Rb: Schoenes et al. (2008)'

In [34]:
with open(r'D:\code\curie\data\dft\ground_truth\2023_09_22_0ce1b5ea9a8637db5435g.json', 'r') as f:
    data = json.load(f)
print(data)

{'code': 'from copy import deepcopy\nfrom json import loads\n\nimport ase\nimport numpy as np\nfrom ase import Atoms\nfrom ase.dft import DOS\nfrom ase.optimize import BFGS\nfrom pydantic import BaseModel, Field\n\nfrom annotations.models.DFTParametersGeneral import DFTParametersGeneral\nfrom annotations.models.StructureMetadata import StructureMetadata\n\n# Functions Code\n\n\n\ndef structure_from_metadata(\n    metadata: StructureMetadata,\n) -> Atoms:\n    pass\n\n\n\n### Key maps\n\nvasp_map = {\n    "exchange_correlation_functional": "xc",\n    "kpoints": "kpts",\n    "pseudopotentials": "pp",\n    "energy_cutoff": "encut",\n    "energy_convergence_criterion": "ediff",\n}\n\ncrystal_map = {\n    "exchange_correlation_functional": "xc",\n    "spin": "spinpol"\n    "basis_set": "basis",\n    "kpoints": "kpts",\n    "ase_otherkeys": "otherkeys"\n}\n\ngaussian_map = {\n    "exchange_correlation_functional": "xc",\n    "basis_set": "basis",\n    "ase_otherkeys": "extra"\n}\n\nsiesta_ma